---
# tasks/derive_custom.yml - Derive ISO custom images from global custom_images

- name: derive iso custom images from global custom_images
  ansible.builtin.set_fact:
    iso_custom_images: "{{ iso_custom_images + [{'name': item.name, 'url': item.url}] }}"
  loop: "{{ custom_images | default([]) }}"
  when: item.url is defined and item.name is defined
